---

- name: ensure requiered repository keys are available
  apt_key:
    url: {{ item }}
    state: present
  loop:
    - https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - https://apt.2ndquadrant.com/site/keys/9904CD4BD6BAF0C3.asc

- name: ensure requiered repositories are configured
  apt_repository:
    repo: {{ item.repo }}
    state: present
    filename: {{ item.file }}
  loop:
    - repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
      file: postgresql
    - repo: "deb https://apt.2ndquadrant.com/ {{ ansible_lsb.codename }}-2ndquadrant main"
      file: repmgr

- name: update repositories cache and install necessary packages
  apt:
    name:
      - ca-certificates
      - postgresql-{{ pg_ver }}
      - postgresql-contrib-{{ pg_ver }}
      - {{ repmgr }}
    state: present
    update_cache: yes
  environment:
    # do not start services after installing them
    RUNLEVEL: 1

