---

- name: Set initial facts
  ansible.builtin.import_tasks: facts.yaml

- name: Execute common setup tasks
  ansible.builtin.import_tasks: common.yaml

- name: SSH key exchange
  ansible.builtin.import_tasks: ssh_key_exchange.yaml

- name: Execute tasks for primary node
  ansible.builtin.import_tasks: primary.yaml
  when: pg_node_is_primary | bool

- name: Execute tasks for replica node
  ansible.builtin.import_tasks: replica.yaml
  when: not pg_node_is_primary | bool
