---

- name: set node id
  set_fact:
    pg_node_id : "{{ 1000 | random(seed=inventory_hostname) }}"

- name: set node as a replica
  set_fact:
    pg_is_primary: false
  when: ansible_hostname != pg_primary

- name: set node as a primary
  set_fact:
    pg_is_primary: true
  when: ansible_hostname == pg_primary

- debug:
    msg: "{{ ansible_hostname }} -> primary node"
  when: ansible_hostname == pg_primary

- debug:
    msg: "{{ ansible_hostname }} -> replica node"
  when: ansible_hostname != pg_primary
